source 'https://rubygems.org'
ruby '2.3.1'

gem 'middleman'
gem 'middleman-livereload'
gem 'rake'
gem 'sassc'
gem 'slim'
gem 'middleman-dotenv'
gem 'bourbon'
gem 'neat'
gem 'builder'
gem 'contentful_middleman', :git => 'https://github.com/contentful/contentful_middleman.git', :branch => 'dl/upgrade-to-v4'
